name: sr_env
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
  - pyg
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.12.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libopus=1.3
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - openh264=1.8.0
  - openjpeg=2.3.0
  - openssl=3.2.0
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pooch=1.7.0
  - pot=0.9.3
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytorch=2.1.0
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qtconsole-base=5.4.4
  - qtpy=2.4.0
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - x264=1!152.20180806
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - click==8.1.7
      - docker-pycreds==0.4.0
      - gdown==5.1.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - joblib==1.3.2
      - numpy==1.24.4
      - protobuf==4.25.2
      - psutil==5.9.6
      - pyparsing==3.1.1
      - scikit-learn==1.3.1
      - scipy==1.10.1
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - setuptools==68.2.2
      - smmap==5.0.1
      - threadpoolctl==3.2.0
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - tqdm==4.66.1
      - wandb==0.16.2
